[package]
name = "procedure_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc_macro = true


[dependencies]
chrono = "0.4.31"
quote = "1.0.35"
syn = "2.0.48"
